package logsim.view;

import java.awt.FileDialog;
import java.awt.Point;
import java.util.List;
import java.util.Map;
import javax.swing.UIManager;
import logsim.Controller;

/**
 *
 */
public class Frame extends javax.swing.JFrame implements FrameView {

    private final Controller controller;

    /**
     * Lekérdezhetõ a vezérlõt
     * @return
     */
    @Override
    public Controller getController() {
        return controller;
    }

    /**
     * Kontruktor
     * @param controller Vezérlõ
     */
    public Frame(Controller controller) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }

        this.controller = controller;
        initComponents();
        this.circuitView.setParent(this);
    }

    /**
     * Megjelenítés
     */
    @Override
    public void makeItVisible() {
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutDialog = new javax.swing.JDialog();
        aboutCloseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        stepBtn = new javax.swing.JButton();
        stateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        circuitView = new logsim.view.CircuitView();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadCircuitMI = new javax.swing.JMenuItem();
        loadConfigMI = new javax.swing.JMenuItem();
        saveConfigMI = new javax.swing.JMenuItem();
        sep = new javax.swing.JPopupMenu.Separator();
        exitMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutMI = new javax.swing.JMenuItem();

        aboutDialog.setTitle("Névjegy");
        aboutDialog.setResizable(false);

        aboutCloseBtn.setText("Bezárás");
        aboutCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutCloseBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LogSim");

        jLabel3.setText("<html>Digitális áramkör szimuláló program, mely a<br>Szoftver Labor 4 címû tárgy keretében készült<br>el a 2010/2011-es tanév második félévében.");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setText("<html><b>Készítették</b>:<br>Apagyi Gábor<br>Dévényi Attila<br>Jákli Gábor<br>Kriván Bálint<br>Péter Tamás Pál");

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(aboutCloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap())
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutCloseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogSim");

        stepBtn.setText("Léptetés");
        stepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepBtnActionPerformed(evt);
            }
        });

        stateLabel.setText("...");

        jLabel1.setText("Szimuláció állapota:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stateLabel)
                .addContainerGap(283, Short.MAX_VALUE))
            .addComponent(stepBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(circuitView, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(circuitView, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stateLabel)))
        );

        jMenu1.setText("Fájl");

        loadCircuitMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        loadCircuitMI.setText("Áramkör betöltés");
        loadCircuitMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCircuitMIActionPerformed(evt);
            }
        });
        jMenu1.add(loadCircuitMI);

        loadConfigMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        loadConfigMI.setText("Konfig betöltés");
        loadConfigMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadConfigMIActionPerformed(evt);
            }
        });
        jMenu1.add(loadConfigMI);

        saveConfigMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveConfigMI.setText("Konfig mentése");
        saveConfigMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveConfigMIActionPerformed(evt);
            }
        });
        jMenu1.add(saveConfigMI);
        jMenu1.add(sep);

        exitMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMI.setText("Kilépés");
        exitMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMIActionPerformed(evt);
            }
        });
        jMenu1.add(exitMI);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Egyéb");

        aboutMI.setText("Névjegy");
        aboutMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMIActionPerformed(evt);
            }
        });
        jMenu2.add(aboutMI);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Léptetés gomb eseményvezérlõje
     * @param evt
     */
    private void stepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepBtnActionPerformed
        controller.onStep();
    }//GEN-LAST:event_stepBtnActionPerformed

    /**
     * Áramkör betöltése menüpont eseményvezérlõje
     * @param evt
     */
    private void loadCircuitMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCircuitMIActionPerformed
        FileDialog fd = new FileDialog(this, "Áramkör betöltés", FileDialog.LOAD);
        fd.setFile("*.txt");
        fd.setDirectory(".\\");
        fd.setLocation(50, 50);
        fd.setVisible(true);
        String fileName = fd.getFile();
        if (fileName != null) {
            controller.loadCircuit(fileName);
        }
    }//GEN-LAST:event_loadCircuitMIActionPerformed

    /**
     * Konfig fájl betöltése menüpont eseményvezérlõje
     * @param evt
     */
    private void loadConfigMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadConfigMIActionPerformed
        FileDialog fd = new FileDialog(this, "Konfig betöltés", FileDialog.LOAD);
        fd.setFile("*.txt");
        fd.setDirectory(".\\");
        fd.setLocation(50, 50);
        fd.setVisible(true);
        String fileName = fd.getFile();
        if (fileName != null) {
            controller.loadConfiguration(fileName);
        }
    }//GEN-LAST:event_loadConfigMIActionPerformed

    /**
     * Konfig fájl mentése menüpont eseményvezérlõje
     * @param evt
     */
    private void saveConfigMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveConfigMIActionPerformed
        FileDialog fd = new FileDialog(this, "Konfig mentés", FileDialog.LOAD);
        fd.setFile("*.txt");
        fd.setDirectory(".\\");
        fd.setLocation(50, 50);
        fd.setVisible(true);
        String fileName = fd.getFile();
        if (fileName != null) {
            controller.saveConfiguration(fileName);
        }
    }//GEN-LAST:event_saveConfigMIActionPerformed

    /**
     * Kilépés menüpont eseményvezérlõje
     * @param evt
     */
    private void exitMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMIActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMIActionPerformed

    /**
     * Névjegy menüpont eseményvezérlõje
     * @param evt
     */
    private void aboutMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMIActionPerformed
        aboutDialog.pack();
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMIActionPerformed

    /**
     * Névjegy ablak bezárása
     * @param evt
     */
    private void aboutCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutCloseBtnActionPerformed
        aboutDialog.setVisible(false);
    }//GEN-LAST:event_aboutCloseBtnActionPerformed

    /**
     * Áramkör szimulációja sikeres
     */
    @Override
    public void onSuccessfulSimulation() {
        stateLabel.setText("STABIL");
    }

    /**
     * Áramkör szimulációja nem sikerült
     */
    @Override
    public void onFailedSimulation() {
        stateLabel.setText("INSTABIL !!!");
    }

    /**
     * Áramkör kirajzolása
     */
    @Override
    public void drawCircuit() {
        circuitView.refresh();
    }

    /**
     * Megjelenítendõ objektumok és koordinátáik átadása a megjelenítõnek
     * @param drawables Megjelenítendõ objektumok
     * @param positions Koordináták
     */
    @Override
    public void setDrawables(List<Drawable> drawables, Map<Drawable, Point> positions) {
        circuitView.updateDrawables(drawables, positions);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutCloseBtn;
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JMenuItem aboutMI;
    private logsim.view.CircuitView circuitView;
    private javax.swing.JMenuItem exitMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem loadCircuitMI;
    private javax.swing.JMenuItem loadConfigMI;
    private javax.swing.JMenuItem saveConfigMI;
    private javax.swing.JPopupMenu.Separator sep;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JButton stepBtn;
    // End of variables declaration//GEN-END:variables
}
